<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Submenu;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SubmenuSeeder extends Seeder
{
    public function run()
    {
      Submenu::truncate();

        $now = Carbon::now();
        $submenus = array(

                array('menu_id' => '2','name' => 'About','name_guj' => 'વિશે','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => 'Where Children','display_heading_guj' => 'ક્યાં બાળકો','display_subheading' => 'Go To Be Educated','display_subheading_guj' =>'શૈક્ષણિક થવા માટે જાઓ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Vision & Mission','name_guj' => 'વિઝન અને મિશન','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => 'Vision &','display_heading_guj' => 'દ્રષ્ટિ &','display_subheading' => 'Mission','display_subheading_guj' =>'મિશન','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
              array('menu_id' => '2','name' => 'Location','name_guj' => 'સ્થાન','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => 'Where We','display_heading_guj' => 'જ્યાં અમે','display_subheading' => 'are Located','display_subheading_guj' =>'સ્થિત છે','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
          array('menu_id' => '2','name' => 'Historical Foundation','name_guj' => 'ઐતિહાસિક ફાઉન્ડેશન','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => 'Historical','display_heading_guj' => 'ઐતિહાસિક','display_subheading' => 'Foundation','display_subheading_guj' =>'ફાઉન્ડેશન','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
          array('menu_id' => '2','name' => "Founder's Philosophy",'name_guj' => 'સ્થાપકની ફિલસૂફી','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => "Founder's",'display_heading_guj' => 'સ્થાપકની','display_subheading' => 'Philosophy','display_subheading_guj' =>'તત્વજ્ઞાન','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'), 

            array('menu_id' => '2','name' => "Members",'name_guj' => 'સભ્યો','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => "Trustees",'display_heading_guj' => 'ટ્રસ્ટીઓ','display_subheading' => '& Members','display_subheading_guj' =>'અને સભ્યો','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),  

            array('menu_id' => '3','name' => "Academic Objectives",'name_guj' => 'શૈક્ષણિક ઉદ્દેશ્યો','sort_id' => '7','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'About SNKKV','display_title_guj' => 'SNKKV વિશે','display_heading' => "Academic",'display_heading_guj' => 'એકેડમિક','display_subheading' => 'Objectives','display_subheading_guj' =>'ઉદ્દેશ્યો','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

            array('menu_id' => '4','name' => "Counselling Cell",'name_guj' => 'કાઉન્સેલિંગ સેલ','sort_id' => '8','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'Counselling Cell','display_title_guj' => 'કાઉન્સેલિંગ સેલ','display_heading' => "Guidance &",'display_heading_guj' => 'માર્ગદર્શન અને','display_subheading' => 'Counselling','display_subheading_guj' =>'કાઉન્સેલિંગ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

            array('menu_id' => '4','name' => "Career Counselling",'name_guj' => 'કારકિર્દી પરામર્શ','sort_id' => '9','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'Counselling Cell','display_title_guj' => 'કાઉન્સેલિંગ સેલ','display_heading' => "Guidance &",'display_heading_guj' => 'માર્ગદર્શન અને','display_subheading' => 'Counselling','display_subheading_guj' =>'કાઉન્સેલિંગ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

           array('menu_id' => '6','name' => "Curricular Facilities",'name_guj' => 'અભ્યાસક્રમ સુવિધાઓ','sort_id' => '10','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'Facilities at SNKKV','display_title_guj' => 'SNKKV ખાતે સુવિધાઓ','display_heading' => "Curricular",'display_heading_guj' => 'અભ્યાસક્રમ','display_subheading' => 'Facilities','display_subheading_guj' =>'સુવિધાઓ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'), 

          array('menu_id' => '6','name' => "Co-Curricular Facilities ",'name_guj' => 'સહ-અભ્યાસક્રમ સુવિધાઓ','sort_id' => '11','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_title' => 'Facilities at SNKKV','display_title_guj' => 'SNKKV ખાતે સુવિધાઓ','display_heading' => "Co-Curricular",'display_heading_guj' => 'સહ અભ્યાસક્રમ','display_subheading' => 'Facilities','display_subheading_guj' =>'સુવિધાઓ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),   

    
        
        );


        foreach ($submenus as &$item) {
          // Get the "name" field value
          $name = $item['name'];
          
          // Generate slug by converting to lowercase and replacing spaces with hyphens
          $slug = str_replace(' ', '-', strtolower($name));
          
          // Store the generated slug in the "slug" field
          $item['slug'] = $slug;
      }
      // Now you can proceed with inserting the updated data into the database
      foreach ($submenus as $submenu) {
          DB::table('submenus')->insert($submenu);
      }
    }
}
