<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Submenu;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SubmenuSeeder extends Seeder
{
    public function run()
    {
      Submenu::truncate();

        $now = Carbon::now();
        $submenus = array(

                array('menu_id' => '2','name' => 'About','name_guj' => 'વિશે','sort_id' => '1','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => 'ABOUT SNKKV','display_subheading' => 'About Us','display_heading_guj' => 'વિશે','display_subheading_guj' =>'અમારા વિશે','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
                array('menu_id' => '2','name' => 'Vision & Mission','name_guj' => 'વિઝન અને મિશન','sort_id' => '2','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => 'About SNKKV','display_subheading' => 'VISION & MISSION','display_heading_guj' => 'SNKKV વિશે','display_subheading_guj' =>'
                દ્રષ્ટિ & મિશન','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
              array('menu_id' => '2','name' => 'Location','name_guj' => 'સ્થાન','sort_id' => '3','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => 'About SNKKV','display_subheading' => 'WHERE WE ARE LOCATED','display_heading_guj' => 'વિશે SNKKV','display_subheading_guj' =>'અમે જ્યાં સ્થિત છીએ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
          array('menu_id' => '2','name' => 'Historical Foundation','name_guj' => 'ઐતિહાસિક ફાઉન્ડેશન','sort_id' => '4','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => 'About SNKKV','display_subheading' => 'Historical Foundation','display_heading_guj' => 'SNKKV વિશે','display_subheading_guj' =>'ઐતિહાસિક ફાઉન્ડેશન','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),
          array('menu_id' => '2','name' => "Founder's Philosophy",'name_guj' => 'સ્થાપકની ફિલસૂફી','sort_id' => '5','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "ABOUT SNKKV",'display_subheading' => "FOUNDER'S PHILOSOPHY",'display_heading_guj' => 'SNKKV વિશે','display_subheading_guj' =>'સ્થાપક ફિલોસોફી','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'), 

            array('menu_id' => '2','name' => "Members",'name_guj' => 'સભ્યો','sort_id' => '6','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "ABOUT SNKKV",'display_subheading' => "Members",'display_heading_guj' => 'SNKKV વિશે ','display_subheading_guj' =>'સભ્યો','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),  

            array('menu_id' => '3','name' => "Academic Objectives",'name_guj' => 'શૈક્ષણિક ઉદ્દેશ્યો','sort_id' => '7','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "ABOUT SNKKV",'display_subheading' => "Academic Objectives",'display_heading_guj' => 'SNKKV વિશે','display_subheading_guj' =>'શૈક્ષણિક ઉદ્દેશ્યો','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

            array('menu_id' => '4','name' => "Counselling Cell",'name_guj' => 'કાઉન્સેલિંગ સેલ','sort_id' => '8','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "COUNSELLING CELL",'display_subheading' => "GUIDANCE & COUNSELLING",'display_heading_guj' => 'કાઉન્સિલિંગ સેલ','display_subheading_guj' =>'માર્ગદર્શન અને પરામર્શ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

            array('menu_id' => '4','name' => "Career Counselling",'name_guj' => 'કારકિર્દી પરામર્શ','sort_id' => '9','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "COUNSELLING CELL",'display_subheading' => "GUIDANCE & COUNSELLING",'display_heading_guj' => 'કાઉન્સિલિંગ સેલ','display_subheading_guj' =>'માર્ગદર્શન અને પરામર્શ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),

           array('menu_id' => '6','name' => "Curricular Facilities",'name_guj' => 'અભ્યાસક્રમ સુવિધાઓ','sort_id' => '10','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "FACILITIES AT SNKKV",'display_subheading' => "CURRICULAR FACILITIES",'display_heading_guj' => 'SNKKV ખાતે સુવિધાઓ','display_subheading_guj' =>'અભ્યાસક્રમ સુવિધાઓ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'), 

          array('menu_id' => '6','name' => "Co-Curricular Facilities ",'name_guj' => 'સહ-અભ્યાસક્રમ સુવિધાઓ','sort_id' => '11','cms' => 'No','pname' => NULL,'image' => NULL,'thumbnail' => NULL,'url_link' => NULL,'display_heading' => "FACILITIES AT SNKKV",'display_subheading' => "CO-CURRICULAR FACILITIES",'display_heading_guj' => 'SNKKV ખાતે સુવિધાઓ','display_subheading_guj' =>'સહ-અભ્યાસક્રમ સુવિધાઓ','slug' => 'location','seo_title' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat','seo_description' => 'We believe that educating a girl is equal to educating a family. Our institution is associated with education along with preservation of customs and culture. We teach our students to treat everyone with respect and humility. To achieve all round development and character building the school has a strict discipline policy.','seo_keywords' => 'Shri Nandkunverba Kshatriya Kanya Vidyalaya - Bhavnagar, Gujrat, Co-educational, residential school, CBSE','status' => 'Active','ip_address' => NULL,'login' => NULL,'deleted_at' => NULL,'created_at' => '2023-08-16 16:55:06','updated_at' => '2023-08-16 16:55:06'),   

    
        
        );


        foreach ($submenus as &$item) {
          // Get the "name" field value
          $name = $item['name'];
          
          // Generate slug by converting to lowercase and replacing spaces with hyphens
          $slug = str_replace(' ', '-', strtolower($name));
          
          // Store the generated slug in the "slug" field
          $item['slug'] = $slug;
      }
      // Now you can proceed with inserting the updated data into the database
      foreach ($submenus as $submenu) {
          DB::table('submenus')->insert($submenu);
      }
    }
}
